# Your name and what you do
name: Steven Carlson
bio: Software Engineer / Security Champion Lead

description: Steven Carlson's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://rockrunner007.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: rockrunner
linkedin: stevenmatthewcarlson
github: rockrunner007
email: steven.carlson007@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: false

# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - HTML, Jade
    - CSS (Stylus, Sass, Less)
    - Javascript, NodeJS
    - AngularJS, ReactJS
    - Java, Android
    - Python
    - MySQL - MongoDB    
    - Git    

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Security_Programs:
        name: Security Programs
        description: Collection of programs for a DevOps team with security top of mind
        url: https://github.com/RockRunner007/Security-Programs
    Security_Automation:
        name: Security Automation 
        description: Role definition and responsible team
        url: https://github.com/RockRunner007/security-automation
    SM_Automation:
        name: Secrets Management Automation
        description: Python project for helping with the operational side of secrets management
        url: https://github.com/RockRunner007/SM_Automation
    SCA_Automation:
        name: Software Component Analysis Automation
        description: Python project for helping with the operational side of software component management
        url: https://github.com/RockRunner007/SCA_Automation
    SAST_Automation:
        name: Static Application Security Testing Automation
        description: Python project for helping with the operational side of sast management
        url: https://github.com/RockRunner007/SAST_Automation
    DAST_Automation:
        name: Dynamic Application Security Testing Automation
        description: Python project for helping with the operational side of dast management
        url: https://github.com/RockRunner007/DAST_Automation


# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
